spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: booking
    password: booking
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jakarta:
          persistence:
            lock:
              timeout: 3000
  flyway:
    enabled: true
    locations: classpath:db/migration

studio:
  timezone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
