name: build-verify

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4

      - name: Run mvn verify
        run: C:\tools\maven\bin\mvn.cmd verify
